#! /usr/bin/env bash
##############################################################################
# Check that all the "version" strings defined are consistent                #
##############################################################################

sedx () {
	sed                              \
	  --quiet                        \
	  --regexp-extended              \
	  --expression                   \
	  's/^.*'"$1"'.*$/\1/;TX;p;q;:X' \
	  "$2"                           ;
}

declare vers_readme=$(sedx 'Version: \*([^*]*)\*' README.markdown)

declare vers_addon=$(jq --raw-output '.version' addon-info.json)

if [[ "${vers_readme}" != "${vers_addon}"  ]]
then
	cat >&2 <<-END_OF_ERROR
	Version do not match!
	    Readme        : |${vers_readme}|
	    Addon         : |${vers_addon}|
	END_OF_ERROR
	exit 1
fi

exit 0
